#!/bin/zsh

theMessage=$(fortune -e)

gxmessage $theMessage -center -title "Take action" -geometry 500 -wrap -font "DejaVu Sans 8" -default "Exit" -buttons "_Cancel":1,"_Reboot":2,"_Shut down":3,"_KillX":4 >/dev/null

case $? in
    1)
        echo "Exit";;
    2)
        sudo systemctl reboot;;
    3)
        sudo systemctl poweroff;;
    4)
        sudo pkill X
esac

