#!/usr/bin/env zsh
# Copyright rejuvyesh <mail@rejuvyesh.com>, 2016
# License: GNU GPLv3 (or later) <http://www.gnu.org/copyleft/gpl.html>

connect() {
  if [[ $(hostname) == 'kusanagi' ]]; then
      xrandr --output eDP1 --auto --output HDMI2 --auto --panning 3840x2160+2880+0 --scale 2x2 --right-of eDP1
  fi
}

disconnect() {
  if [[ $(hostname) == 'kusanagi' ]]; then
     xrandr --output HDMI2 --off
  fi
}

case "$1" in
  connect)
    connect
    ;;
  disconnect)
    disconnect
    ;;
  *)
    echo "connect or disconnect?"
esac
