#!/usr/bin/env zsh

# Easier find

if [[ "$1" == "--help" ]]; then
  echo "usage: fin <expr> [dirs...]"
  exit
fi

expr="$1"
shift

if [[ "$#" == "0" ]]; then
  find . -xdev | ag "$expr"
else
  while (( "$#" )); do
    find "$1" -xdev | ag "$expr"
    shift
  done
fi
