#!/bin/zsh

# Created by rejuvyesh <rejuvyesh@gmail.com>

phone_type=android
program=$0
usage() {
    cat <<EOM
    Usage:
    $program setup     -   Mount phone as an mtp device
    $program unmount   -   Unmount phone as an mtp device
    $program mv        -   Copy photos from phone to camera directory
    $program cleanup   -   Remove photos from phone 
EOM
    exit 0
}

[[ -z $1 ]] && { usage; }

if [[ "$1" = cleanup ]]; then
    echo "Removing downloaded photos from phone..."

    case $phone_type in
        android)
            printf "removing photos"
            rm -f ~/android/SD\ card/DCIM/*/* || true
            sleep 1
            ;;
    esac
    exit 0
fi
if [[ "$1" = setup ]]; then
    printf "Waiting for phone..."
    case $phone_type in
        android)
            go-mtpfs ~/android
            echo
            ;;
    esac
    exit 0
fi

if [[ "$1" = unmount ]]; then
    printf "unmounting phone..."
    case $phone_type in
        android)
            fusermount -u ~/android
            echo done
            ;;
    esac
fi
if [[ "$1" = mv ]]; then
    cd ~/images/camera/
    subdir="$(date +%F_%H:%M)"
    mkdir -p "$subdir"
    rm -f latest
    ln -sf "$subdir" latest

    case "$phone_type" in
        android)
            cp -v ~/android/SD\ card/DCIM/*/* "./$subdir/"
            fonefoto cleanup
            ;;
        *)
            echo "bad phone type $phone_type" >&2
            exit 1
    esac

    rmdir * 2>/dev/null || true # weed empty dirs
    git annex add .
    git commit -m "add $subdir"
fi
