#!/usr/bin/env ruby
# -*- encoding: utf-8 -*-
# Copyright rejuvyesh <mail@rejuvyesh.com>, 2014
# License: GNU GPL 3 <http://www.gnu.org/copyleft/gpl.html>

require 'muflax'

File.load('~/.hs_packages').each do |line|
  next if (line.starts_with? '#') || line.chomp!.blank?

  pkg = line.strip
  if pkg.index(/:path/)
    path = pkg.partition('=>').last
    package = pkg.partition('=>').first.split(' ').first
    puts path
    ap "Installing #{package}"
    Dir.chdir(eval path)
    system 'cabal install'
  else
    puts "getting #{pkg}..."
    system "cabal install #{pkg}"
  end

end
