#!/usr/bin/env ruby
# -*- encoding: utf-8 -*-
# Copyright rejuvyesh <mail@rejuvyesh.com>, 2014
# License: GNU GPL 3 <http://www.gnu.org/copyleft/gpl.html>

require 'epitools'
require 'awesome_print'
require 'pry'

def mpv_identify(filename)
  output = %x(mpv_identify.sh "#{filename}")
  clip_info  = {}
  video_info = {}
  audio_info = {}
  info       = {}
  output.lines.each do |line|
    
    if line =~ /([\da-z_]+)=(.+)$/
      name, val = $1, $2
      
      case name
      when /clip_info_(name|value)(\d)+/
        clip_info[$2] ||= {}
        clip_info[$2][$1.downcase] = val
      when 'exit', 'demuxer', 'clip_info_n', 'filename', 'seekable'
        # skip it
      when /video_(.+)/
        video_info[$1.downcase] = val
      when /audio_(.+)/
        audio_info[$1.downcase] = val
      else
        info[name.downcase] = val
      end

    end
  end

  keyvals = clip_info.map do |k, v|
    [v['name'], v['value']]
  end

  clip_info_unsorted = Hash[ *keyvals.flatten ]

  clip_info_keys = [
                    'title',
                    'artist',
                    'date',
                    'creation_time',
                    'album',
                    'genre',
                   ]

  clip_info = Hash[*clip_info_keys.map {|key| \
                     [key, clip_info_unsorted.delete(key)] \
                     if clip_info_unsorted[key] }.compact.flatten]
  clip_info.merge!(clip_info_unsorted)

  {
    'metadata' => clip_info,
    'video' => video_info,
    'audio' => audio_info,
    'info' => info,
  }
end

if $0 == __FILE__
  if ARGV.any?
    lesspipe do |less|
      ARGV.each do |arg|
        less.puts "<8>### <14>#{arg} <8>#{"#"*30}".colorize
        less.puts
        less.puts mpv_identify(arg).ai
        less.puts
      end
    end
  else
    puts 'Usage: mpv-info <video file(s)...>'
  end
end
