#!/usr/bin/env ruby

books = Dir.glob(File.expand_path("~/books/*pdf")).map{|b| File.basename(b)}
chosen = `echo "#{books.join("\n")}" | dmenu`
system "zathura ~/books/#{chosen}" unless chosen.empty?
