#!/usr/bin/env ruby
# -*- encoding: utf-8 -*-
# Copyright rejuvyesh <mail@rejuvyesh.com>, 2015
# License: GNU GPL 3 <http://www.gnu.org/copyleft/gpl.html>

require 'shellwords'
PAPERS_DIR = '/home/rejuvyesh/papers'

if __FILE__ == $PROGRAM_NAME
  if ARGV.any?
    Dir.chdir PAPERS_DIR
    ARGV.each do |u|
      puts "## URL: #{u}"
      cmd = "wget #{u} -O tmp.pdf"
      system(*cmd)
      new = `paper-rename -f tmp.pdf`
      puts "## Adding to git-annex"
      system("git-annex addurl --file #{Shellwords.escape(new.strip)} #{u.strip}")
    end
  else
    puts
    puts 'Usage: paper <url1> [<url2>, ...]'
    puts
    puts 'Purpose:'
    puts '  Download pdf, rename it to human friendly name and'
    puts '  add to git-annex with the url.'
  end
end
