#!/bin/zsh
# Copyright muflax <muflax@gmail.com>, 2009
# License: GNU GPL 3 <http://www.gnu.org/copyleft/gpl.html>

DIR="$HOME/images/selection"
TARGET="$DIR/selection-$(date "+%F[%H:%M:%S]").png"
LATEST="$DIR/latest.png"
DISPLAY=:0.0 import +repage -quality 100 -silent png:$TARGET
echo $TARGET
rm -f "$LATEST"
ln -sf "$TARGET" "$LATEST"
