#!/bin/zsh

# Created by rejuvyesh <mail@rejuvesh.com>

# fume

fume_db=$(ruby -ryaml << EOF
c = YAML.load_file(File.join(ENV['HOME'], '.fumerc'))
puts File.join(c['fume_dir'], 'fume_db.yaml')
EOF
)

watch_fume() {
    mod_time=$(stat -c "%Y" $fume_db)
    now=$(date "+%s")

    if [[ $mod_time -gt $last_mod_time ]]; then
      last_mod_time=$mod_time
      ti display --start 'today 0:00' -f status 
    elif [[ $now -gt $(( $last_mod_time + 600 )) ]]; then
      last_mod_time=$now
      ti display --start 'today 0:00' -f status
    fi
}
watch_fume
