#!/usr/bin/env ruby
# -*- encoding: utf-8 -*-
#
# File: fumeup.rb
#
# Copyright rejuvyesh <mail@rejuvyesh.com>, 2014
# License: GNU GPL 3 <http://www.gnu.org/copyleft/gpl.html>

require 'yaml'

config = YAML.load_file(File.join(ENV['HOME'], '.fumerc'))
fume_db = File.join(config['fume_dir'], 'fume_db.yaml')

last_mod_time = 0
mod_time = File.mtime(fume_db).to_i
now =  Time.now.to_i

if mod_time > last_mod_time
  last_mod_time = mod_time
  puts `ti display --start 'today 0:00' -f status`
elsif now > last_mod_time + 600
  last_mod_time = now
  puts `ti display --start 'today 0:00' -f status`
end
