#!/bin/zsh

# this is a simple operation, really. all we do is fetch data from last.fm, get
# the albm cover links, download them, and put them in the right place.
# There are no heuristics going on here, it only works on exact matches!

(( $# != 2 )) && echo 'Usage: $0 Artist Album' && return 1

if [[ -e $1/$2.xpm ]]; then
    echo "Error: File exists: $1/$2.xpm"
    return 2
fi

echo "Fetching Artist $1, Album $2..."

# simple http get request for album.getinfo, with artist + album
data=$(curl \
    --data-urlencode method=album.getinfo \
    --data-urlencode api_key=2f63459bcb2578a277c5cf5ec4ca62f7 \
    --data-urlencode artist=$1 \
    --data-urlencode album=$2 \
    -G -s http://ws.audioscrobbler.com/2.0/)

[[ $? > 0 ]] && echo 'Error: Unable to fetch album data!' && return 3

# try to find a cover art link
setopt rematchpcre
[[ $data =~ '<image size="medium">([^<]+)</image>' ]] || { echo 'Error: No cover art found in album info.' && return 4 }

echo "Found data url: $match"

1=${1:gs/\//_}
2=${2:gs/\//_}

# make sure this dir exists..
if [[ ! -d $1 ]]; then
    echo "Creating $1.."
    mkdir $1
fi

# download and convert. heh.
echo 'Downloading and converting..'
curl -s $match | convert - -resize 64x64 "$1/$2.xpm"

[[ $? == 0 ]] && echo 'All done!' || { echo 'Error fetching or converting..' && return 5 }
